# Generated by Django 4.2 on 2023-06-26 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nuuseapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="QA_en",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("answer", models.TextField()),
            ],
        ),
    ]
